spring:
  application:
    name: MedPlatform

  flyway:
    enabled: true

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      # ddl-auto: update
      # ddl-auto: create
      ddl-auto: validate # Validates
      #ddl-auto: none
      # ddl-auto: delete
