spring:
  application:
    name: MedPlatform

  flyway:
    enabled: true
    baseline-on-migrate: true

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: AuthHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      # ddl-auto: update
      # ddl-auto: create
      ddl-auto: validate # Validates
      #ddl-auto: none
      # ddl-auto: delete

      show-sql: true
      format-sql: true
      use-sql-comments: true
      open-in-view: false
      jdbc:
        batch_size: 25 # Optimizes databank sequences
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: kafka-broker:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1 # Acknowledgment from leader is enough for fast logging
      retries: 3
      properties:
        linger.ms: 10
        batch.size: 16400 # 16KB batch size before sending to broker

    consumer:
      group-id: auth-logger-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

